type: Model
name: product_classification_example
index: id
target: label
columns:
  - type: TEXT
    name: text
  - type: CATEGORICAL
    name: label
train:
  metric: accuracy
  schedule: 0 0 1 * *
  exclude_ensemble: True
  disable_automl_feature_generation: True
  disable_feature_timestamp_generation: True
  disable_feature_importance: True
  size: xxlarge
  included_model_types:
    - distilbert
    - Catboost
    - XGBoost
    - GBM
predict:
  schedule: 0 2 1 * *
  incremental: True
promote:
  policy: best
table: tmls.cfpb.micro_consumer_complaints
